### ISSUE TITLE
RJ format has changed 

### ISSUE THREAD

**Issue by asuka431** [yodhcn/dlsite-doujin-renamer#10]
https://github.com/yodhcn/dlsite-doujin-renamer/blob/main/main.py#L162
behold, dlsite extended RJ format like below. it is bless to us but need a little change.
https://www.dlsite.com/maniax/work/=/product_id/RJ01003500.html/

**Comment by yodhcn** [comment]
> 

https://github.com/yodhcn/dlsite-doujin-renamer/commit/c24b53631075c897ed7f686d3937d2dcd1f479e3

**Comment by asuka431** [comment]
＿○／|＿　forgivevmy rudeness
