### ISSUE TITLE
将图片设置为文件夹封面这个功能可以单独分出来一个软件吗

### ISSUE THREAD

**Issue by deadblue0910** [yodhcn/dlsite-doujin-renamer#14]
之前都是用ps加个透明正方形背景再转换ico然后设图标的，一直想找个快捷点的方法

**Comment by yodhcn** [comment]
这个软件的一个贡献者 [Determancer](https://github.com/Determancer) 写过一个类似的小工具，我直接搬过来了。

https://mega.nz/file/l75UkSLQ#JIPuzOWk7nT5sox8XQyAqXLWpOIT-TGjCTt9TkB7tFg
