### ISSUE TITLE
希望能添加VJ号查询或是根据名字关键字查询

### ISSUE THREAD

**Issue by zcx761105** [yodhcn/dlsite-doujin-renamer#15]
dl上除了RJ号也还有VJ号啥的
希望能添加一个搜索VJ号的 如果更改太过麻烦
也希望能加个根据名字关键字来查询的功能 这样会更加方便
谢谢您

**Comment by yodhcn** [comment]
done

https://github.com/yodhcn/dlsite-doujin-renamer/releases/tag/0.2.8
