### ISSUE TITLE
作品聲優有多位只會抓取一位

### ISSUE THREAD

**Issue by pp-2** [yodhcn/dlsite-doujin-renamer#22]
作品聲優有多位只會抓取一位 還是有其他相關設定?

**Comment by yodhcn** [comment]
> 作品聲優有多位只會抓取一位 還是有其他相關設定?

没有限制CV数量的设定，我使用时也没有遇到过你说的这种情况。
能否举个例子说明一下？

**Comment by pp-2** [comment]
抱歉是我看錯 RJ號了 另外想請教一下 抓取CV時 有沒有可以定義符號來區隔 CV
