### ISSUE TITLE
爬取元数据失败

### ISSUE THREAD

**Issue by ret130** [yodhcn/dlsite-doujin-renamer#26]
爬取元数据失败[ConnectionError]：HTTPSConnectionPool(host='www.dlsite.com', port=443): Max retries exceeded with url: /maniax/api/=/product.json?workno=RJ281027&locale=zh_cn (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000193B7E69CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

**Comment by yodhcn** [comment]
这不算BUG，只是网络问题，是重试次数达到上限抛出的异常，重试几次就行。

**Comment by ret130** [comment]
感谢大佬问题解决了
