### ISSUE TITLE
有些音声抓取到的封面会显示为noimage图标

### ISSUE THREAD

**Issue by Ryuset** [yodhcn/dlsite-doujin-renamer#28]
举个栗子，RJ01147426 这个音声抓取后封面是 no image 的显示图标。 有相当一部分的音声作品在抓取封面的时候出现这种情况。请问该怎么解决。

https://www.dlsite.com/maniax/work/=/product_id/RJ01147426.html

![sample2 (2)](https://github.com/yodhcn/dlsite-doujin-renamer/assets/96915900/cbab31fb-250c-4512-be94-38c78fe5801b)

**Comment by yodhcn** [comment]
RJ01147426 有封面啊，不应该出现这种情况。

可能是请求 DLsite Api 时，DLsite 那边的数据还没更新？若是这样，尝试以下操作：
1. step1 **删除缓存文件** `cache.db`
2. step2 **删除文件夹的封面图片** `@folder-icon-RJ01147426.ico`，这是个被操作系统隐藏的文件，用 [Everything](https://www.voidtools.com/support/everything/) 软件搜索对应的 RJ 号可以快速找到该文件；或者，将文件夹中的内容移动到新文件夹中，再将旧文件夹删除

**Comment by Ryuset** [comment]
感谢回复，尝试清除缓存后解决问题😊。希望该issue对后面遇到同样问题的朋友们有帮助。
