### ISSUE TITLE
修改标签顺序无法生效

### ISSUE THREAD

**Issue by LemonSoda-RPG** [yodhcn/dlsite-doujin-renamer#4]
修改标签顺序无法生效，有更加具体的例子吗

**Comment by yodhcn** [comment]
这里以 [RJ298293](https://www.dlsite.com/maniax/work/=/product_id/RJ298293.html) 为例
配置1：
```json
{
  "scaner_max_depth": 5,
  "scraper_locale": "zh_cn",
  "scraper_connect_timeout": 10,
  "scraper_read_timeout": 10,
  "scraper_sleep_interval": 3,
  "scraper_http_proxy": "127.0.0.1:7890",
  "renamer_template": "[rjcode] work_name (tags_list_str)",
  "renamer_exclude_square_brackets_in_work_name_flag": false,
  "renamer_illegal_character_to_full_width_flag": false,
  "renamer_delimiter": " ",
  "renamer_tags_max_number": 5,
  "renamer_tags_ordered_list": [
    "标签1",
    [
      "标签2",
      "替换2"
    ],
    "标签3"
  ]
}
```
结果1：
```[RJ298293] 【ツルセンター耳かきぴんこ団子】蓄音レヱル 紅【CV.黒沢ともよ】 (萌 感动 治愈 环绕音 ASMR)```

配置2：
```
{
  "scaner_max_depth": 5,
  "scraper_locale": "zh_cn",
  "scraper_connect_timeout": 10,
  "scraper_read_timeout": 10,
  "scraper_sleep_interval": 3,
  "scraper_http_proxy": "127.0.0.1:7890",
  "renamer_template": "[rjcode] work_name (tags_list_str)",
  "renamer_exclude_square_brackets_in_work_name_flag": false,
  "renamer_illegal_character_to_full_width_flag": false,
  "renamer_delimiter": " ",
  "renamer_tags_max_number": 5,
  "renamer_tags_ordered_list": [
    "ASMR",
    [
      "萌",
      "Moe"
    ],
    "掏耳"
  ]
}
```
结果2：
```[RJ298293] 【ツルセンター耳かきぴんこ団子】蓄音レヱル 紅【CV.黒沢ともよ】 (ASMR Moe 掏耳 感动 治愈)```

RJ298293 简中页面下的标签为 ```tag_list = ["萌", "感动", "治愈", "环绕音", "ASMR", "少女", "掏耳", "低语"]```
配置1 & 配置2 中，```renamer_tags_max_number``` 都设为 ```5```
- 配置1 中 ```renamer_tags_ordered_list``` 保持默认配置，直接取 ```tag_list``` 的前 5 个标签；
- 配置2 中，我们设置了 ```renamer_tags_ordered_list```，程序会先按照 ```renamer_tags_ordered_list``` 将标签重新排序为 ```tag_list_ordered = ["ASMR", "Moe", "掏耳", "感动", "治愈", "环绕音", "少女", "低语"]```，再取 ```tag_list_ordered``` 的前 5 个标签。

只设置 ```renamer_tags_max_number```，程序不知道你偏好哪些标签，你认为比较重要的标签可能会被舍弃。
所以，在 ```renamer_tags_max_number``` 设置得比较小时，```renamer_tags_ordered_list``` 里应当包含你认为比较重要的标签，并按重要程度排序，最重要的标签放在最前面。

**Comment by LemonSoda-RPG** [comment]
理解了 感谢
